import { rnd, setRndSeed, UInt32Array } from "../shared";

beforeAll(() => {
  //
  // This code is used for Node.js environment for the tests
  //
  if (!ArrayBuffer.prototype.transfer) {
    ArrayBuffer.prototype.transfer = function transfer(len) {
      if (!(this instanceof ArrayBuffer)) throw new TypeError('Source must be an instance of ArrayBuffer')
      if (len <= this.byteLength) return this.slice(0, len)
      const sourceView = new Uint8Array(this)
      const destView = new Uint8Array(new ArrayBuffer(len))
      destView.set(sourceView)
      return destView.buffer
    }
  }
})

describe('Shared functions', () => {
  describe('rnd() function logic', () => {
    it('Resetting seed to the same value should get us the same rnd() result', () => {
      setRndSeed(1)
      const v0 = rnd()
      setRndSeed(1)
      const v1 = rnd()
      expect(v0).toBe(v1)
    })
  })

  describe('UInt32Array class', () => {
    it('should create a UInt32Array with 1 slot', () => {
      const a = UInt32Array.create(1)
      expect(a.i).toBe(0)
      expect(a.end()).toBe(false)
      a.add(42)
      expect(a[0]).toBe(42)
      expect(a.end()).toBe(true)
    })
    it('should create a UInt32Array with 0 size', () => {
      const a = UInt32Array.create(0)
      expect(a.end()).toBe(true)
      expect(a.i < 0).toBe(true)
    })
    it('should create a UInt32Array with size 2 and add two values without errors', () => {
      const a = UInt32Array.create(2)
      expect(a.end()).toBe(false)
      a.add(42)
      a.add(43)
      expect(a.i).toBe(2)
      expect(a[0]).toBe(42)
      expect(a[1]).toBe(43)
      expect(a.end()).toBe(true)
    })
    it('creating two arrays will not affect each other', () => {
      const a = UInt32Array.create(2)
      const b = UInt32Array.create(2)
      a.add(42)
      b.add(43)
      expect(a[0]).toBe(42)
      expect(a.has(42)).toBe(true)
      expect(a.has(43)).toBe(false)
      expect(b[0]).toBe(43)
      expect(b.has(42)).toBe(false)
      expect(b.has(43)).toBe(true)
    })
    it('resize() should double the size of the array', () => {
      let a = UInt32Array.create(1)
      a.add(42)
      expect(a.end()).toBe(true)
      a = a.resize(2)
      expect(a.end()).toBe(false)
      a.add(44)
      expect(a[1]).toBe(44)
      expect(a.end()).toBe(true)
      expect(a.i).toBe(2)
    })
    it('resize() should reduce array size if size is less than current', () => {
      let a = UInt32Array.create(2)
      a.add(42)
      a.add(43)
      expect(a.end()).toBe(true)
      a = a.resize(1)
      expect(a.end()).toBe(true)
      expect(a[0]).toBe(42)
      expect(a.i).toBe(1)
    })
    it('has() should return true if value exists in the array', () => {
      const a = UInt32Array.create(2)
      expect(a.has(42)).toBe(false)
      expect(a.has(43)).toBe(false)
      a.add(42)
      expect(a.has(42)).toBe(true)
      expect(a.has(43)).toBe(false)
      a.del(0)
      expect(a.i).toBe(0)
      expect(a.has(42)).toBe(false)
      expect(a.has(43)).toBe(false)
    })
    it('has() should work event after size reduce after resize()', () => {
      let a = UInt32Array.create(2)
      a.add(42)
      a.add(43)
      expect(a.has(42)).toBe(true)
      expect(a.has(43)).toBe(true)
      a = a.resize(1)
      expect(a.has(42)).toBe(true)
      expect(a.has(43)).toBe(false)
    })
    it('has() should work if we remove a value in the center of the array', () => {
      const a = UInt32Array.create(3)
      a.add(42)
      a.add(43)
      a.add(44)
      expect(a.has(42)).toBe(true)
      expect(a.has(43)).toBe(true)
      expect(a.has(44)).toBe(true)
      a.del(1)
      expect(a.has(42)).toBe(true)
      expect(a.has(43)).toBe(false)
      expect(a.has(44)).toBe(true)
    })
    it('index() should return index of the value inside array', () => {
      const a = UInt32Array.create(2)
      expect(a.index(42)).toBe(-1)
      expect(a.index(43)).toBe(-1)
      a.add(42)
      expect(a.index(42)).toBe(0)
      expect(a.index(43)).toBe(-1)
      a.add(43)
      expect(a.index(42)).toBe(0)
      expect(a.index(43)).toBe(1)
      a.del(0)
      expect(a.index(42)).toBe(-1)
      expect(a.index(43)).toBe(0)
    })
    it('index() should work correctly after array resize', () => {
      let a = UInt32Array.create(2)
      a.add(42)
      a.add(43)
      expect(a.index(42)).toBe(0)
      expect(a.index(43)).toBe(1)
      a = a.resize(1)
      expect(a.index(42)).toBe(0)
      expect(a.index(43)).toBe(-1)
    })
    it('index() should work correctly after removing an element from the array', () => {
      const a = UInt32Array.create(2)
      a.add(42)
      a.add(43)
      expect(a.index(42)).toBe(0)
      expect(a.index(43)).toBe(1)
      a.del(0)
      expect(a.index(42)).toBe(-1)
      expect(a.index(43)).toBe(0)
      a.add(44)
      expect(a.index(42)).toBe(-1)
      expect(a.index(43)).toBe(0)
      expect(a.index(44)).toBe(1)
    })
    it('index() should work if we remove a value in the center of the array', () => {
      const a = UInt32Array.create(3)
      a.add(42)
      a.add(43)
      a.add(44)
      expect(a.index(42)).toBe(0)
      expect(a.index(43)).toBe(1)
      expect(a.index(44)).toBe(2)
      a.del(1)
      expect(a.index(42)).toBe(0)
      expect(a.index(43)).toBe(-1)
      expect(a.index(44)).toBe(1)
    })
    it('double() should double the size of the array', () => {
      let a = UInt32Array.create(1)
      a.add(42)
      expect(a.end()).toBe(true)
      a = a.double()
      expect(a.end()).toBe(false)
      a.add(44)
      expect(a[1]).toBe(44)
      expect(a.end()).toBe(true)
      expect(a.i).toBe(2)
      expect(a.has(42)).toBe(true)
      expect(a.has(44)).toBe(true)
    })
    it('double() twice should double the size twice', () => {
      let a = UInt32Array.create(1)
      a.add(42)
      expect(a.end()).toBe(true)
      a = a.double()
      expect(a.end()).toBe(false)
      a.add(44)
      expect(a.has(44)).toBe(true)
      expect(a.end()).toBe(true)
      expect(a.i).toBe(2)

      a = a.double()
      expect(a.end()).toBe(false)
      a.add(45)
      expect(a.has(45)).toBe(true)
      expect(a.end()).toBe(false)
      expect(a.i).toBe(3)
    })
    it('end() should return true for the empty array', () => {
      const a = UInt32Array.create(0)
      expect(a.end()).toBe(true)
    })
    it('end() should work correctly if array is resized', () => {
      let a = UInt32Array.create(2)
      a.add(42)
      a.add(43)
      expect(a.end()).toBe(true)
      a = a.resize(1)
      expect(a.end()).toBe(true)
      a = a.resize(2)
      a.add(44)
      expect(a.end()).toBe(true)
      a.del(0)
      expect(a.end()).toBe(false)
    })
   it('add() should add value to the array', () => {
      const a = UInt32Array.create(2)
      expect(a.i).toBe(0)
      a.add(42)
      expect(a.i).toBe(1)
      expect(a[0]).toBe(42)
      a.add(43)
      expect(a.i).toBe(2)
      expect(a[1]).toBe(43)
      a.del(1)
      expect(a.has(43)).toBe(false)
      expect(a.end()).toBe(false)
      a.add(43)
      expect(a.has(43)).toBe(true)
    })
  })
});